version: "3.9"
services:
  backend:
    image: ghcr.io/znyinc/canadian-legal-assistant-backend:latest
    environment:
      NODE_ENV: production
      DATABASE_URL: file:./prisma/dev.db
    ports:
      - "3001:3001"
    volumes:
      - backend-db:/app/prisma
  frontend:
    image: ghcr.io/znyinc/canadian-legal-assistant-frontend:latest
    ports:
      - "5173:80"
    depends_on:
      - backend
volumes:
  backend-db: